name:                midihaskey
version:             0.1.0.0
github:              "unclechu/midihaskey"
license:             GPL-3
author:              "Viacheslav Lotsmanov"
maintainer:          "Viacheslav Lotsmanov <lotsmanov89@gmail.com>"
copyright:           "2018 Viacheslav Lotsmanov"
category:            Audio
synopsis:            Virtual MIDI keyboard for microtonal music

description:
  Virtual MIDI keyboard for microtonal music.
  .
  TODO more description info.

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base-unicode-symbols
  - bytestring
  - data-default
  - directory
  - filepath
  - glib
  - gtk3
  - hashable
  - linux-evdev
  - midi
  - process
  - qm-interpolated-string
  - scientific
  - singletons
  - text
  - transformers
  - unordered-containers

ghc-options:
  - -O2

library:
  source-dirs: src

executables:
  midihaskey:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - midihaskey
