name:                midihaskey-utils
version:             0.1.0.0
github:              "unclechu/midihaskey"
license:             GPL-3
author:              "Viacheslav Lotsmanov"
maintainer:          "Viacheslav Lotsmanov <lotsmanov89@gmail.com>"
copyright:           "2018 Viacheslav Lotsmanov"
category:            Audio
synopsis:            Some generic utils functions for the MIDIHasKey

description:
  Some generic utils functions for the MIDIHasKey

dependencies:
  - base >= 4.7 && < 5
  - base-unicode-symbols
  - midi
  - qm-interpolated-string

ghc-options:
  - -O2

library:
  source-dirs: src
